name: Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      #- name: Configure cache
      #  uses: Swatinem/rust-cache@v2

      - name: Build release binary
        run: cargo build --release
        env:
          # https://rust-lang.github.io/rfcs/1721-crt-static.html
          RUSTFLAGS: -C target-feature=+crt-static

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: release_cli
          path: target/release/windows_tts_cli.exe

      - name: Build release dll and installer
        run: cargo build --release --workspace
        env:
          # https://rust-lang.github.io/rfcs/1721-crt-static.html
          RUSTFLAGS: -C target-feature=+crt-static

      - name: Upload engine dll
        uses: actions/upload-artifact@v4
        with:
          name: release_dll
          path: target/release/windows_tts_engine.dll

      - name: Upload engine installer
        uses: actions/upload-artifact@v4
        with:
          name: release_installer
          path: target/release/windows_tts_engine_installer.exe

  piper-build:
    name: Build piper text-to-speech engine
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      #- name: Configure cache
      #  uses: Swatinem/rust-cache@v2

      - name: Build release dll
        run: cargo build --release --package windows_tts_engine_piper_dll

      - name: Upload engine dll
        uses: actions/upload-artifact@v4
        with:
          name: release_piper_dll
          path: target/release/windows_tts_engine_piper.dll

  release:
    name: Release
    runs-on: windows-latest
    needs: [build, piper-build]
    permissions:
      contents: write
    steps:
      - name: Download cli from previous job
        uses: actions/download-artifact@v4
        with:
          name: release_cli

      - name: Download dll from previous job
        uses: actions/download-artifact@v4
        with:
          name: release_dll

      - name: Download piper dll from previous job
        uses: actions/download-artifact@v4
        with:
          name: release_piper_dll

      - name: Download installer from previous job
        uses: actions/download-artifact@v4
        with:
          name: release_installer

      # Create the release:  https://github.com/actions/create-release
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{github.ref}}
          release_name: windows_text_to_speech ${{ github.ref }}
          draft: false
          prerelease: false

      # Upload release asset:   https://github.com/actions/upload-release-asset
      - name: Upload release asset (cli)
        id: upload-release-asset-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: windows_tts_cli.exe
          asset_name: windows_tts_cli.exe
          # https://stackoverflow.com/questions/41459168/which-mime-type-is-correct-for-the-exe-file
          asset_content_type: application/vnd.microsoft.portable-executable
          # asset_content_type: application/zip

      - name: Upload release asset (dll)
        id: upload-release-asset-dll
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: windows_tts_engine.dll
          asset_name: windows_tts_engine.dll
          # https://stackoverflow.com/questions/41459168/which-mime-type-is-correct-for-the-exe-file
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload release asset (piper dll)
        id: upload-release-asset-piper-dll
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: windows_tts_engine_piper.dll
          asset_name: windows_tts_engine_piper.dll
          # https://stackoverflow.com/questions/41459168/which-mime-type-is-correct-for-the-exe-file
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload release asset (dll installer)
        id: upload-release-asset-installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: windows_tts_engine_installer.exe
          asset_name: windows_tts_engine_installer.exe
          # https://stackoverflow.com/questions/41459168/which-mime-type-is-correct-for-the-exe-file
          asset_content_type: application/vnd.microsoft.portable-executable
